reviewers:
  # The default reviewers
  defaults:
      - petati
      - fopanin
      
  # Reviewer groups each of which has a list of GitHub usernames.
  groups:
    core-reviewers:
      - petati
      - fopanin
    leads-reviewers:
      - pirelo4472

files: 
  # Keys are glob expressions.
  # You can assign groups defined above as well as GitHub usernames.
  '**':
    - core-reviewers

# Randomly pick reviewers up to this number.
# Do not set this option if you'd like to assign all matching reviewers.
# number_of_reviewers: 10
