name: Add reviewers to PR
on:
  pull_request: 
    types: [opened, reopened]

env: 
 # Change variable to add reviewers with comma separator.
 # Example: `sakhnovict, dbitkovski, chernodub`.
 # Users should be codeowners or collaborators to review.
 FIRST_STEP_REVIEWERS: 'petati'
    
jobs:
  onOpenedPullRequest:
    runs-on: ubuntu-latest
    steps:
    - name: add-reviewers-action
      uses: sakhnovict/add-reviewers-action@1.0.0
      with: 
        reviewers: ${{ env.FIRST_STEP_REVIEWERS }}
        token: ${{ secrets.GITHUB_TOKEN }}
