name: 2-Stage PR Approval Proccess
on:
  pull_request: 
    types: [opened]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - run: echo "PR is opened"
    - name: Add Pull Request Reviewer
      uses: AveryCameronUofR/add-reviewer-gh-action@1.0.3
      with: 
        reviewers: "petati"
        token: ${{ secrets.GITHUB_TOKEN }}
