name: Check should add team leads to PR review
on:
  pull_request_review:
    types: [submitted]

env:
  APPROVALS_TO_CALL_LEADS: 2
  
  # Change variable to add reviewers with comma separator.
  # Example: `sakhnovict, dbitkovski, chernodub`.
  # Users should be codeowners or collaborators to review.
  TEAM_LEADS_REVIEWERS: 'pirelo4472'
    
jobs:
  onSubmit:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: multi-approved-event
        uses: sakhnovict/multi-approved-event-action@1.0.9
        id: approved
        with:
          approvalsCount: ${{ env.APPROVALS_TO_CALL_LEADS }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: add-reviewers-action
        uses: sakhnovict/add-reviewers-action@1.0.0
        with: 
          reviewers: ${{ env.TEAM_LEADS_REVIEWERS }}
          token: ${{ secrets.GITHUB_TOKEN }}
        if: steps.approved.outputs.isApproved == 'true'
