name: Check should add lead reviewers to PR
on:
  pull_request_review:
    types: [submitted]

env:
  APPROVALS_TO_CALL_LEADS: 2

jobs:
  onSubmit:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      # Analyze approvals data.
      - name: multi-approved-event
        uses: sakhnovict/multi-approved-event-action@1.0.9
        id: approved
        with:
          approvalsCount: ${{ env.APPROVALS_TO_CALL_LEADS }}
          onlyEqual: 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      # Add Leads to Pull Request review, if reached the required number of approvals.
      - name: Request lead reviewers.
        uses: necojackarc/auto-request-review@v0.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config: .github/lead-reviewers.yml
        if: steps.approved.outputs.isApproved == 'true'
        
      # Disable this workflow to ensure that this workflow will be triggered only once.
      - name: Disable this workflow to ensure that this workflow will be triggered only once
        shell: bash
        run: |
          gh workflow disable -R $GITHUB_REPOSITORY "${{ github.workflow }}"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        if: steps.approved.outputs.isApproved == 'true'
