on: pull_request_review
name: Example Job
jobs:
  myJob:
    runs-on: ubuntu-latest
    steps:
    - uses: taichi/approved-event-action@v1.2.1
      id: approved
      with:
        approvals: '2'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: echo "Approved !!"
      if: steps.approved.outputs.approved == 'true'
